name: Workflow Demo

on: 
  push
## repo variable added
env:
  ACCESS_ID: ${{ secrets.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID
